/**
 * Key code mappings for keyboard input handling
 * Based on the codes used by uiohook-napi
 */

export const KeyCodes = {
  // Basic keys
  Backspace: 14,
  Tab: 15,
  Enter: 28,
  CapsLock: 58,
  Escape: 1,
  Space: 57,
  PageUp: 3657,
  PageDown: 3665,
  End: 3663,
  Home: 3655,
  ArrowLeft: 57419,
  ArrowUp: 57416,
  ArrowRight: 57421,
  ArrowDown: 57424,
  Insert: 3666,
  Delete: 3667,
  
  // Numbers
  0: 11,
  1: 2,
  2: 3,
  3: 4,
  4: 5,
  5: 6,
  6: 7,
  7: 8,
  8: 9,
  9: 10,
  
  // Letters
  A: 30,
  B: 48,
  C: 46,
  D: 32,
  E: 18,
  F: 33,
  G: 34,
  H: 35,
  I: 23,
  J: 36,
  K: 37,
  L: 38,
  M: 50,
  N: 49,
  O: 24,
  P: 25,
  Q: 16,
  R: 19,
  S: 31,
  T: 20,
  U: 22,
  V: 47,
  W: 17,
  X: 45,
  Y: 21,
  Z: 44,
  
  // Numpad
  Numpad0: 82,
  Numpad1: 79,
  Numpad2: 80,
  Numpad3: 81,
  Numpad4: 75,
  Numpad5: 76,
  Numpad6: 77,
  Numpad7: 71,
  Numpad8: 72,
  Numpad9: 73,
  NumpadMultiply: 55,
  NumpadAdd: 78,
  NumpadSubtract: 74,
  NumpadDecimal: 83,
  NumpadDivide: 3637,
  NumpadEnter: 3612,
  NumpadEnd: 3663, 
  NumpadArrowDown: 57424,
  NumpadPageDown: 3665,
  NumpadArrowLeft: 57419,
  NumpadArrowRight: 57421,
  NumpadHome: 3655,
  NumpadArrowUp: 57416,
  NumpadPageUp: 3657,
  NumpadInsert: 3666,
  NumpadDelete: 3667,
  
  // Function keys
  F1: 59,
  F2: 60,
  F3: 61,
  F4: 62,
  F5: 63,
  F6: 64,
  F7: 65,
  F8: 66,
  F9: 67,
  F10: 68,
  F11: 87,
  F12: 88,
  F13: 91,
  F14: 92,
  F15: 93,
  F16: 99,
  F17: 100,
  F18: 101,
  F19: 102,
  F20: 103,
  F21: 104,
  F22: 105,
  F23: 106,
  F24: 107,
  
  // Special characters
  Semicolon: 39,
  Equal: 13,
  Comma: 51,
  Minus: 12,
  Period: 52,
  Slash: 53,
  Backquote: 41,
  BracketLeft: 26,
  Backslash: 43,
  BracketRight: 27,
  Quote: 40,
  
  // Modifiers
  Ctrl: 29,
  CtrlRight: 3613,
  Alt: 56,
  AltRight: 3640,
  Shift: 42,
  ShiftRight: 54,
  Meta: 3675,
  MetaRight: 3676,
  
  // Other
  NumLock: 69,
  ScrollLock: 70,
  PrintScreen: 3639
};

// Mapping from browser KeyboardEvent.code to our key codes
export const BrowserKeyCodeMap: Record<string, number> = {
  // Common mappings
  'Space': KeyCodes.Space,
  'ControlLeft': KeyCodes.Ctrl,
  'AltLeft': KeyCodes.Alt,
  'ShiftLeft': KeyCodes.Shift,
  'ShiftRight': KeyCodes.ShiftRight,
  'AltRight': KeyCodes.AltRight,
  'ControlRight': KeyCodes.CtrlRight,
  'Escape': KeyCodes.Escape,
  'Backspace': KeyCodes.Backspace,
  'Tab': KeyCodes.Tab,
  'CapsLock': KeyCodes.CapsLock,
  'Enter': KeyCodes.Enter,
  'NumpadEnter': KeyCodes.NumpadEnter,
  'NumLock': KeyCodes.NumLock,
  'Home': KeyCodes.Home,
  'End': KeyCodes.End,
  'PageUp': KeyCodes.PageUp,
  'PageDown': KeyCodes.PageDown,
  'ArrowLeft': KeyCodes.ArrowLeft,
  'ArrowUp': KeyCodes.ArrowUp,
  'ArrowRight': KeyCodes.ArrowRight,
  'ArrowDown': KeyCodes.ArrowDown,
  'Insert': KeyCodes.Insert,
  'Delete': KeyCodes.Delete,
  
  // Letters
  'KeyA': KeyCodes.A,
  'KeyB': KeyCodes.B,
  'KeyC': KeyCodes.C,
  'KeyD': KeyCodes.D,
  'KeyE': KeyCodes.E,
  'KeyF': KeyCodes.F,
  'KeyG': KeyCodes.G,
  'KeyH': KeyCodes.H,
  'KeyI': KeyCodes.I,
  'KeyJ': KeyCodes.J,
  'KeyK': KeyCodes.K,
  'KeyL': KeyCodes.L,
  'KeyM': KeyCodes.M,
  'KeyN': KeyCodes.N,
  'KeyO': KeyCodes.O,
  'KeyP': KeyCodes.P,
  'KeyQ': KeyCodes.Q,
  'KeyR': KeyCodes.R,
  'KeyS': KeyCodes.S,
  'KeyT': KeyCodes.T,
  'KeyU': KeyCodes.U,
  'KeyV': KeyCodes.V,
  'KeyW': KeyCodes.W,
  'KeyX': KeyCodes.X,
  'KeyY': KeyCodes.Y,
  'KeyZ': KeyCodes.Z,
  
  // Numbers
  'Digit0': KeyCodes[0],
  'Digit1': KeyCodes[1],
  'Digit2': KeyCodes[2],
  'Digit3': KeyCodes[3],
  'Digit4': KeyCodes[4],
  'Digit5': KeyCodes[5],
  'Digit6': KeyCodes[6],
  'Digit7': KeyCodes[7],
  'Digit8': KeyCodes[8],
  'Digit9': KeyCodes[9],
  
  // Numpad
  'Numpad0': KeyCodes.Numpad0,
  'Numpad1': KeyCodes.Numpad1,
  'Numpad2': KeyCodes.Numpad2,
  'Numpad3': KeyCodes.Numpad3,
  'Numpad4': KeyCodes.Numpad4,
  'Numpad5': KeyCodes.Numpad5,
  'Numpad6': KeyCodes.Numpad6,
  'Numpad7': KeyCodes.Numpad7,
  'Numpad8': KeyCodes.Numpad8,
  'Numpad9': KeyCodes.Numpad9,
  'NumpadMultiply': KeyCodes.NumpadMultiply,
  'NumpadAdd': KeyCodes.NumpadAdd,
  'NumpadSubtract': KeyCodes.NumpadSubtract,
  'NumpadDecimal': KeyCodes.NumpadDecimal,
  'NumpadDivide': KeyCodes.NumpadDivide,
  
  // Function keys
  'F1': KeyCodes.F1,
  'F2': KeyCodes.F2,
  'F3': KeyCodes.F3,
  'F4': KeyCodes.F4,
  'F5': KeyCodes.F5,
  'F6': KeyCodes.F6,
  'F7': KeyCodes.F7,
  'F8': KeyCodes.F8,
  'F9': KeyCodes.F9,
  'F10': KeyCodes.F10,
  'F11': KeyCodes.F11,
  'F12': KeyCodes.F12,
  'F13': KeyCodes.F13,
  'F14': KeyCodes.F14,
  'F15': KeyCodes.F15,
  'F16': KeyCodes.F16,
  'F17': KeyCodes.F17,
  'F18': KeyCodes.F18,
  'F19': KeyCodes.F19,
  'F20': KeyCodes.F20,
  'F21': KeyCodes.F21,
  'F22': KeyCodes.F22,
  'F23': KeyCodes.F23,
  'F24': KeyCodes.F24,
  
  // Special characters
  'Semicolon': KeyCodes.Semicolon,
  'Equal': KeyCodes.Equal,
  'Comma': KeyCodes.Comma,
  'Minus': KeyCodes.Minus,
  'Period': KeyCodes.Period,
  'Slash': KeyCodes.Slash,
  'Backquote': KeyCodes.Backquote,
  'BracketLeft': KeyCodes.BracketLeft,
  'Backslash': KeyCodes.Backslash,
  'BracketRight': KeyCodes.BracketRight,
  'Quote': KeyCodes.Quote
};

// Mapping from key codes to display names for UI
export const KeyDisplayMap: Record<string, string> = {
  [KeyCodes.Space.toString()]: 'Space',
  [KeyCodes.Ctrl.toString()]: 'Left Ctrl',
  [KeyCodes.Alt.toString()]: 'Left Alt',
  [KeyCodes.Shift.toString()]: 'Left Shift',
  [KeyCodes.ShiftRight.toString()]: 'Right Shift',
  [KeyCodes.AltRight.toString()]: 'Right Alt',
  [KeyCodes.CtrlRight.toString()]: 'Right Ctrl',
  [KeyCodes.Escape.toString()]: 'Escape',
  [KeyCodes.Backspace.toString()]: 'Backspace',
  [KeyCodes.Tab.toString()]: 'Tab',
  [KeyCodes.CapsLock.toString()]: 'Caps Lock',
  [KeyCodes.Enter.toString()]: 'Enter',
  [KeyCodes.NumpadEnter.toString()]: 'Num Enter',
  [KeyCodes.NumLock.toString()]: 'Num Lock',
  [KeyCodes.Home.toString()]: 'Home',
  [KeyCodes.End.toString()]: 'End',
  [KeyCodes.PageUp.toString()]: 'Page Up',
  [KeyCodes.PageDown.toString()]: 'Page Down',
  [KeyCodes.ArrowLeft.toString()]: 'Left Arrow',
  [KeyCodes.ArrowUp.toString()]: 'Up Arrow',
  [KeyCodes.ArrowRight.toString()]: 'Right Arrow',
  [KeyCodes.ArrowDown.toString()]: 'Down Arrow',
  [KeyCodes.Insert.toString()]: 'Insert',
  [KeyCodes.Delete.toString()]: 'Delete',
  
  // Letters
  [KeyCodes.A.toString()]: 'A',
  [KeyCodes.B.toString()]: 'B',
  [KeyCodes.C.toString()]: 'C',
  [KeyCodes.D.toString()]: 'D',
  [KeyCodes.E.toString()]: 'E',
  [KeyCodes.F.toString()]: 'F',
  [KeyCodes.G.toString()]: 'G',
  [KeyCodes.H.toString()]: 'H',
  [KeyCodes.I.toString()]: 'I',
  [KeyCodes.J.toString()]: 'J',
  [KeyCodes.K.toString()]: 'K',
  [KeyCodes.L.toString()]: 'L',
  [KeyCodes.M.toString()]: 'M',
  [KeyCodes.N.toString()]: 'N',
  [KeyCodes.O.toString()]: 'O',
  [KeyCodes.P.toString()]: 'P',
  [KeyCodes.Q.toString()]: 'Q',
  [KeyCodes.R.toString()]: 'R',
  [KeyCodes.S.toString()]: 'S',
  [KeyCodes.T.toString()]: 'T',
  [KeyCodes.U.toString()]: 'U',
  [KeyCodes.V.toString()]: 'V',
  [KeyCodes.W.toString()]: 'W',
  [KeyCodes.X.toString()]: 'X',
  [KeyCodes.Y.toString()]: 'Y',
  [KeyCodes.Z.toString()]: 'Z',
  
  // Numbers
  [KeyCodes[0].toString()]: '0',
  [KeyCodes[1].toString()]: '1',
  [KeyCodes[2].toString()]: '2',
  [KeyCodes[3].toString()]: '3',
  [KeyCodes[4].toString()]: '4',
  [KeyCodes[5].toString()]: '5',
  [KeyCodes[6].toString()]: '6',
  [KeyCodes[7].toString()]: '7',
  [KeyCodes[8].toString()]: '8',
  [KeyCodes[9].toString()]: '9',
  
  // Numpad
  [KeyCodes.Numpad0.toString()]: 'Numpad 0',
  [KeyCodes.Numpad1.toString()]: 'Numpad 1',
  [KeyCodes.Numpad2.toString()]: 'Numpad 2',
  [KeyCodes.Numpad3.toString()]: 'Numpad 3',
  [KeyCodes.Numpad4.toString()]: 'Numpad 4',
  [KeyCodes.Numpad5.toString()]: 'Numpad 5',
  [KeyCodes.Numpad6.toString()]: 'Numpad 6',
  [KeyCodes.Numpad7.toString()]: 'Numpad 7',
  [KeyCodes.Numpad8.toString()]: 'Numpad 8',
  [KeyCodes.Numpad9.toString()]: 'Numpad 9',
  [KeyCodes.NumpadMultiply.toString()]: 'Numpad *',
  [KeyCodes.NumpadAdd.toString()]: 'Numpad +',
  [KeyCodes.NumpadSubtract.toString()]: 'Numpad -',
  [KeyCodes.NumpadDecimal.toString()]: 'Numpad .',
  [KeyCodes.NumpadDivide.toString()]: 'Numpad /',
  
  // Function keys
  [KeyCodes.F1.toString()]: 'F1',
  [KeyCodes.F2.toString()]: 'F2',
  [KeyCodes.F3.toString()]: 'F3',
  [KeyCodes.F4.toString()]: 'F4',
  [KeyCodes.F5.toString()]: 'F5',
  [KeyCodes.F6.toString()]: 'F6',
  [KeyCodes.F7.toString()]: 'F7',
  [KeyCodes.F8.toString()]: 'F8',
  [KeyCodes.F9.toString()]: 'F9',
  [KeyCodes.F10.toString()]: 'F10',
  [KeyCodes.F11.toString()]: 'F11',
  [KeyCodes.F12.toString()]: 'F12',
  
  // Special characters
  [KeyCodes.Semicolon.toString()]: ';',
  [KeyCodes.Equal.toString()]: '=',
  [KeyCodes.Comma.toString()]: ',',
  [KeyCodes.Minus.toString()]: '-',
  [KeyCodes.Period.toString()]: '.',
  [KeyCodes.Slash.toString()]: '/',
  [KeyCodes.Backquote.toString()]: '`',
  [KeyCodes.BracketLeft.toString()]: '[',
  [KeyCodes.Backslash.toString()]: '\\',
  [KeyCodes.BracketRight.toString()]: ']',
  [KeyCodes.Quote.toString()]: "'"
}; 